// <auto-generated />
using System;
using LinkShortener.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkShortener.Data.Migrations
{
    [DbContext(typeof(MariaDbContext))]
    [Migration("20230922210908_FinalTouches")]
    partial class FinalTouches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LinkShortener.Models.Domain.LinkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("Viewed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 9, 23, 0, 9, 8, 529, DateTimeKind.Local).AddTicks(5544),
                            RawUrl = "https://google.com",
                            ShortUrl = "38fh43",
                            Viewed = 0
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 9, 23, 0, 9, 8, 529, DateTimeKind.Local).AddTicks(5557),
                            RawUrl = "https://youtube.com",
                            ShortUrl = "fG47Kd",
                            Viewed = 420
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 9, 23, 0, 9, 8, 529, DateTimeKind.Local).AddTicks(5558),
                            RawUrl = "https://avtobus1.ru/avtopark/avtobus/45-mest",
                            ShortUrl = "98CsfD",
                            Viewed = 1337
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
